### ISSUE TITLE
Vet Preference Link iframe

### ISSUE THREAD

**Issue by cew821** [usds/website#143]
**This issue was originally reported by @frankydp in the previous repo**
# The Veterans preference information link on the https://www.usds.gov/join#application page attempts to iframe the below link from OPM, which fails for SAMEORIGIN.  The resulting page also ends up in a state were the Apply Now(#application) anchor does not display the form.

https://www.opm.gov/policy-data-oversight/veterans-employment-initiative/vet-guide/#2Types

Urgency 1

![img](http://i.imgur.com/QkfZQ6f.png)

**Comment by unruthless** [comment]
The source code for the link in question isn't in this repository; instead, it's included via an `iframe` containing an embedded Salesforce (?) form.

Is it possible to add a `target="blank"` to the link's anchor tag, so that the OPM page opens in a new window or new tab? In other words, is it possible to change

`Are you a Veteran of the U.S. Armed Forces or are you eligible for "derived" <a href="https://www.opm.gov/policy-data-oversight/veterans-services/vet-guide/#2Types">preference</a>?`

to

`Are you a Veteran of the U.S. Armed Forces or are you eligible for "derived" <a href="https://www.opm.gov/policy-data-oversight/veterans-services/vet-guide/#2Types" target="blank">preference</a>?`

?

This would change the behavior of this link slightly (opening the OPM page in a new browser tab or browser window), and would fix the issue where clicking on the link results in the entire form disappearing.

**Comment by chrisfrommann** [comment]
@briandroberts, can you add `target="blank"` to the link in Salesforce?

**Comment by charwo** [comment]
@briandroberts ping!

**Comment by jas298** [comment]
This is fixed!
