### ISSUE TITLE
Remove the word "Fit" from Final Interview

### ISSUE THREAD

**Issue by neilmartis** [usds/website#259]
Its good to hire people from all walks of life.http://www.forbes.com/sites/erikaandersen/2015/03/17/is-cultural-fit-just-a-new-way-to-discriminate/#60753df273b9

http://fortune.com/2015/12/07/culture-fit-hiring-discrimination/
Sorry I didn't mean to offend anyone about it.I am in the same situation before hence feel the same about others that's all

**Comment by jas298** [comment]
@neilmartis Sorry for the slow response on this! Our "fit" interviews aren't about cultural fit, but rather skill set fit, since we have several different teams with different needs. We completely agree that diversity in all its forms is vital! I'll talk to the team about whether we ought to change this name so it's not confusing. Thanks for flagging!
