### ISSUE TITLE
Application form loses styling when there is an error

### ISSUE THREAD

**Issue by jas298** [usds/website#299]
When I submit an application but miss a required field (or there is another error), the page reloads with the error, but is sub-optimal in three ways:

1. The form loads without styling, which makes it hard to read/identify.
2. The error message is at the bottom of the form, and isn't identifiable in any way; I didn't notice it the first two times through.
3. When the page reloads, you're still at the bottom of it, and you have to scroll up for a while to get to the actual content.

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15876167/25140178/74c11d7c-242d-11e7-886b-c9e09a81d30a.png)

![image](https://cloud.githubusercontent.com/assets/15876167/25140204/827fe5f6-242d-11e7-82a5-40bfc9b3ca30.png)

**Comment by jas298** [comment]
@jaredcunha You mentioned today you might know the cause of this--can you take a look, please? LMK if you need access to Salesforce.

**Comment by jaredcunha-usds** [comment]
I think I figured out the issue. Seems due to relative paths. 

The iframe source is here: 
https://wh45.secure.force.com/digitalserviceform/
The stylesheet link is here: `//www.usds.gov/lib/uswds/css/uswds.min.css`

When you submit the form without the required fields, the form reloads here (notice new directory?):
https://wh45.secure.force.com/digitalserviceform/ApplicationForm
Now the link to the CSS file is `/digitalserviceform//www.usds.gov/lib/uswds/css/uswds.min.css` which results in a 404. 

Not sure how the form functions. The fix would be either reloading the _exact_ page, or using an absolute link to the CSS.

**Comment by jas298** [comment]
@jaredcunha-usds Do you need to look at the form in Salesforce to answer the question of how it works? If so, I'm happy to make that happen!

**Comment by jas298** [comment]
@jaredcunha-usds any chance you can take a look at this again this week? We are having reports of people not being able to submit applications and our strongest hypothesis right now is that they are triggering an error but not seeing it because of these issues.

**Comment by jaredcunha-usds** [comment]
@jas298 The suggestion I have above still stands regarding the styling, so I think that would need to be addressed. There is error messaging at the bottom of the page of the page, but that is easy to miss. We can add `required` attributes to any of the required fields so at least the browser can run validations and prevent the form from submitting. That would be the simplest, easiest fix. However, I'd need to get into salesforce to apply the fix.

**Comment by jas298** [comment]
@jaredcunha-usds Awesome. Can we meet sometime this week for you to take a look in Salesforce under my account? How about 3 PM EDT on Tuesday (before staff meeting)? Just sent you a calendar invitation!

**Comment by jaredcunha-usds** [comment]
@jas298 This should be resolved now. Can you verify?

**Comment by jas298** [comment]
These issues are resolved.
