### ISSUE TITLE
Updating Leaving USDS pop-up when clicking into a blog link 

### ISSUE THREAD

**Issue by nadiay123** [usds/website#366]
@nacingov can we update the banner that comes up when you click into the blogs and it takes you to medium. 
It says we are hiring UX Designers, but we should update that to be engineers
(Also let me know if someone else should be running with this - I'm starting with you!)

**Comment by nadiay123** [comment]
Update: my screenshot won't load 😿

**Comment by ctrimm** [comment]
There is also an issue with external hyperlinks in the modal that utilize `_` underscores instead of `-` dashes. See screenshot below.

I'll take a stab at this sometime this week. Expect a PR before the end of the week.

<img width="882" alt="screen shot 2018-07-02 at 11 29 13 am" src="https://user-images.githubusercontent.com/1751160/42177861-8ad079c8-7deb-11e8-84d4-4b7c920fa221.png">

**Comment by jaredcunha-usds** [comment]
We have launched a refresh of usds.gov. Luckily, these modals are no longer a thing!
