### ISSUE TITLE
Edit cop/job select options on apply page

### ISSUE THREAD

**Issue by drew-usds** [usds/website#482]
Edit dropdown list on apply page -- Laura needs to check w/ Andréa first, though.

This needs to be edited in Salesforce, the `/apply` page pulls in the form through an iframe.

 **Add**
- [x] Content strategy

**Delete**
- [x] Visual design
- [x] Product design

**Comment by LauraUSDS** [comment]
@AndreaViza Do you see any issues with changing the items in the "primary field of expertise" dropdown in our usds application, per the above? Who should we talk to about making that change (@LisaHwang)?

**Comment by AndreaViza** [comment]
We could do that but @LisaHwang this would affect how things flow into SF correct?
That being said, we shouldn't make any changes until the migration happens.

**Comment by LisaHwang** [comment]
We will need to wait until after the migration but the changes are doable. I think there has been some conversation in the past about changing the buckets - we should include someone on the talent team as well to ensure that the buckets make sense. Just note that this will change up metrics for everyone. Pulling reports for past folks will need to know the past and current buckets, might be a nightmare.

**Comment by LauraUSDS** [comment]
Ok, good to know @LisaHwang and makes total sense. @K-Jurick @bernars-usa Are these changes still worth making (editing the field of expertise options for designers)?

**Comment by LisaHwang** [comment]
Actually taking a closer look, this is doable. What a candidate "self-selects" matters less because someone on the talent team moves them to an internal bucket which metrics is based off of. So we're good. I would just need to route it. Outside of that, we would need to coordinate how we want the application buckets to be routed to our internal buckets. i.e Cyber security will get routed to engineering bucket.

**Comment by K-Jurick** [comment]
"Product Design" is super confusing as a term for us. I for one would still like these changes to be made.

**Comment by lisac-usds** [comment]
@bernars-usa @K-Jurick @LauraUSDS, with your input, I applied some changes. Would you please let me know whether there's further work needed on this issue?

Added:
- Content Design/UX Writing
- Content Strategy

Removed:
- Product Design
- Visual Design

snapshot of usds.gov/apply:
<img src="https://user-images.githubusercontent.com/31673962/84568605-88a83200-ad4e-11ea-8e97-e921941accb3.png" width="300">

**Comment by bernars-usa** [comment]
I like it! Thanks, Lisa! 😍

**Comment by K-Jurick** [comment]
I'd add "**user research**" since much like content it is a specialty we always seem to need and I know I was hesitant when I first started talking to USDS recruiting because they kept calling me a "designer" which is our blanket term, but not industry's...I'd also personally keep **visual design** in the mix as we say we don't need it and yet always keep those folks extremely busy - having some backup resumes/candidates even if it is more specialized is not a bad thing from my perspective

**Comment by K-Jurick** [comment]
Who gets the front end candidates? Does this go to Design or Engineering? (this is a longstanding question as we start to see more and more "hybrids" and its harder to know how to evaluate them or where to put them, but the best ones are potentially more Jareds) I'm sure you have been debating this one already...the problem could be somewhat solved by allowing an applicant to pick up to 2 specialties - but I can't remember if we are that fancy

**Comment by K-Jurick** [comment]
Also I realize that what I am saying here now, today, may contradict what I have said in the past. Time, distance and the human condition can all influence perspective is all I can say about that :)

**Comment by lisac-usds** [comment]
updated to account for User Research and Visual Design.  snapshot of usds.gov/apply:
<img src="https://user-images.githubusercontent.com/31673962/84732980-0a74a700-af6b-11ea-9d14-a9ed09c79b88.png" width="350">

Nodding along to your comments about front end candidates, @K-Jurick. Will follow up in a side chat with this group.
